### ISSUE TITLE
add healthcheck endpoint

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-api-events#11]
## Type of Change
- [x] New Endpoint
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary

As [mentioned](https://github.com/ProvidenceGeeks/website-api-events/pull/9#pullrequestreview-73666408) in #5 , a `healthcheck` endpoint should be created in a file called _EventsAPI.java_.

It should just expose 
- an endpoint `/healthcheck`
- return a status response code of `200`
- should return a JSON payload
```
{
  "status": 200,
  "message": "OK"
}
```

**Comment by thescientist13** [comment]
@saimatsumoto 
You can test the endpoint via cURL or in your browser
```
$ curl http://54.208.177.39:8080/healthcheck
{"status":200,"message":"OK"}
```

**Comment by saimatsumoto** [comment]
- [x] TEST: returns expected response. 
`$  curl http://54.208.177.39:8080/healthcheck
{"status":200,"message":"OK"}
`
