### ISSUE TITLE
expose custom GroupPhoto property in events responses

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-api-events#16]
## Type of Change
- [ ] New Endpoint
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary

As part of the work done in https://github.com/ProvidenceGeeks/website-lambda-meetup/issues/11 , `group_photo` was added to the group property in an events response.

This new property needs to be added to the modeled response to clients, so that it can be available to resolve an issue like https://github.com/ProvidenceGeeks/website-frontend/issues/58

**Comment by thescientist13** [comment]
`group_photo` now showing within the `group` property in an event response
http://stage.pvdgeeks.org/api/events

**Comment by saimatsumoto** [comment]
Verified that GroupPhotos return in all data from `/api/events`.
